### PR TITLE
Adding the Polish language

### PR DESCRIPTION
**Pull request by XdekTV**
If there is a way to include registry edits, i will happilly add them, because some of the CPL items are not translated (name only, the rest is fine)

### CODE REVIEW

**Review by ImSwordQueen — COMMENTED** [review]
PosReady has the copyright date set to 2009. Is that how the polish translation did it?

**Review by ImSwordQueen — COMMENTED** [review]
Explorer.exe.mui's menu has news and interests and cortana still listed. I could keep those in but some people might dislike that as it's not accurate to 7 for non LTSC releases.

**Comment by ImSwordQueen** [comment]
Themecpl7.dll.res String Table ID 8 doesn't have "frost" and "Automatic". (Same issue in themecpl.dll.mui.res)
Themeui7.dll.res doesn't have String ID "2015" in String Table ID 126. It might not be important if in the polish translation it was never translated. (and some stuff wasn't removed but i can do that myself later.)

**Comment by XdekTV** [comment]
thanks for the feedback, i will get the files changed asap!

**Comment by XdekTV** [comment]
> Themecpl7.dll.res String Table ID 8 doesn't have "frost" and "Automatic". (Same issue in themecpl.dll.mui.res)
> 
> Themeui7.dll.res doesn't have String ID "2015" in String Table ID 126. It might not be important if in the polish translation it was never translated. (and some stuff wasn't removed but i can do that myself later.)
> 
> Display.dll.mui didn't have some changes that i've highlighted in the wiki (Kinda important because i cannot do these myself as i don't know the language)
> 
> Overall, i appreciate the effort.

before i updated the fixed files, while adding perfcentercpl's mui, i don't have some neccecary strings for Display.dll.mui, in my Windows 7 install. for themecpl7 and themeui7, they were never translated, although there is a 116 in windows 10 called automatic (116 is already changed to be the last color in windows 7)

**Comment by ImSwordQueen** [comment]
> > Themecpl7.dll.res String Table ID 8 doesn't have "frost" and "Automatic". (Same issue in themecpl.dll.mui.res)
> > Themeui7.dll.res doesn't have String ID "2015" in String Table ID 126. It might not be important if in the polish translation it was never translated. (and some stuff wasn't removed but i can do that myself later.)
> > Display.dll.mui didn't have some changes that i've highlighted in the wiki (Kinda important because i cannot do these myself as i don't know the language)
> > Overall, i appreciate the effort.
> 
> before i updated the fixed files, while adding perfcentercpl's mui, i don't have some neccecary strings for Display.dll.mui, in my Windows 7 install. for themecpl7 and themeui7, they were never translated, although there is a 116 in windows 10 called automatic (116 is already changed to be the last color in windows 7)

For display.dll.mui you only need to remove stuff and add one thing: https://github.com/ImSwordQueen/Win10to7LanguagePacks/wiki/3.-Edit-the-.RES-.DLL-.MUI-Files-for-21H2to7#displaydllmui

**Comment by ImSwordQueen** [comment]
> > Themecpl7.dll.res String Table ID 8 doesn't have "frost" and "Automatic". (Same issue in themecpl.dll.mui.res)
> > Themeui7.dll.res doesn't have String ID "2015" in String Table ID 126. It might not be important if in the polish translation it was never translated. (and some stuff wasn't removed but i can do that myself later.)
> > Display.dll.mui didn't have some changes that i've highlighted in the wiki (Kinda important because i cannot do these myself as i don't know the language)
> > Overall, i appreciate the effort.
> 
> before i updated the fixed files, while adding perfcentercpl's mui, i don't have some neccecary strings for Display.dll.mui, in my Windows 7 install. for themecpl7 and themeui7, they were never translated, although there is a 116 in windows 10 called automatic (116 is already changed to be the last color in windows 7)

In 21H2to7 "Frost" and "Automatic" got the names switched. 116 is for automatic and 117 for frost. https://github.com/ImSwordQueen/Win10to7LanguagePacks/wiki/3.-Edit-the-.RES-.DLL-.MUI-Files-for-21H2to7#displaydllmui

**Comment by XdekTV** [comment]
> > > Themecpl7.dll.res String Table ID 8 doesn't have "frost" and "Automatic". (Same issue in themecpl.dll.mui.res)
> > > Themeui7.dll.res doesn't have String ID "2015" in String Table ID 126. It might not be important if in the polish translation it was never translated. (and some stuff wasn't removed but i can do that myself later.)
> > > Display.dll.mui didn't have some changes that i've highlighted in the wiki (Kinda important because i cannot do these myself as i don't know the language)
> > > Overall, i appreciate the effort.
> > 
> > 
> > before i updated the fixed files, while adding perfcentercpl's mui, i don't have some neccecary strings for Display.dll.mui, in my Windows 7 install. for themecpl7 and themeui7, they were never translated, although there is a 116 in windows 10 called automatic (116 is already changed to be the last color in windows 7)
> 
> In 21H2to7 "Frost" and "Automatic" got the names switched. 116 is for automatic and 117 for frost. https://github.com/ImSwordQueen/Win10to7LanguagePacks/wiki/3.-Edit-the-.RES-.DLL-.MUI-Files-for-21H2to7#displaydllmui
> 
> Also, ThemeUI7 has "Windows 7 (dark)" which is the Dark7 theme name which is in the personalization panel. https://github.com/ImSwordQueen/Win10to7LanguagePacks/wiki/3.-Edit-the-.RES-.DLL-.MUI-Files-for-21H2to7#displaydllmui

i will add those right now. thanks for saying that!

**Comment by XdekTV** [comment]
> > > Themecpl7.dll.res String Table ID 8 doesn't have "frost" and "Automatic". (Same issue in themecpl.dll.mui.res)
> > > Themeui7.dll.res doesn't have String ID "2015" in String Table ID 126. It might not be important if in the polish translation it was never translated. (and some stuff wasn't removed but i can do that myself later.)
> > > Display.dll.mui didn't have some changes that i've highlighted in the wiki (Kinda important because i cannot do these myself as i don't know the language)
> > > Overall, i appreciate the effort.
> > 
> > 
> > before i updated the fixed files, while adding perfcentercpl's mui, i don't have some neccecary strings for Display.dll.mui, in my Windows 7 install. for themecpl7 and themeui7, they were never translated, although there is a 116 in windows 10 called automatic (116 is already changed to be the last color in windows 7)
> 
> For display.dll.mui you only need to remove stuff and add one thing: https://github.com/ImSwordQueen/Win10to7LanguagePacks/wiki/3.-Edit-the-.RES-.DLL-.MUI-Files-for-21H2to7#displaydllmui

the problem is, that my windows 7 vm, **doesn't** have that particular string, so i left the one that it came with (8.1's)

**Comment by ImSwordQueen** [comment]
> > > > Themecpl7.dll.res String Table ID 8 doesn't have "frost" and "Automatic". (Same issue in themecpl.dll.mui.res)
> > > > Themeui7.dll.res doesn't have String ID "2015" in String Table ID 126. It might not be important if in the polish translation it was never translated. (and some stuff wasn't removed but i can do that myself later.)
> > > > Display.dll.mui didn't have some changes that i've highlighted in the wiki (Kinda important because i cannot do these myself as i don't know the language)
> > > > Overall, i appreciate the effort.
> > > 
> > > 
> > > before i updated the fixed files, while adding perfcentercpl's mui, i don't have some neccecary strings for Display.dll.mui, in my Windows 7 install. for themecpl7 and themeui7, they were never translated, although there is a 116 in windows 10 called automatic (116 is already changed to be the last color in windows 7)
> > 
> > 
> > For display.dll.mui you only need to remove stuff and add one thing: https://github.com/ImSwordQueen/Win10to7LanguagePacks/wiki/3.-Edit-the-.RES-.DLL-.MUI-Files-for-21H2to7#displaydllmui
> 
> the problem is, that my windows 7 vm, **doesn't** have that particular string, so i left the one that it came with (8.1's)

Oh yeah, I forgot to mention that some strings of display.dll.mui aren't in 7 like "Preview" but are meant to be in those pages (CPL Restoration adds them back) 

image

**Comment by XdekTV** [comment]
now it should have everything that you requested. if you notice something is missing, please tell me.

**Comment by ImSwordQueen** [comment]
> now it should have everything that you requested. if you notice something is missing, please tell me.

LGTM. ThemeCPL has those missing but i can fix that myself later.

For display.dll please refer to this: https://github.com/ImSwordQueen/Win10to7LanguagePacks/pull/7#issuecomment-2395121402

**Comment by XdekTV** [comment]
> > now it should have everything that you requested. if you notice something is missing, please tell me.
> 
> LGTM. ThemeCPL has those missing but i can fix that myself later.
> 
> For display.dll please refer to this: https://github.com/ImSwordQueen/Win10to7LanguagePacks/pull/7#issuecomment-2395121402 and tell me if it doesn't have them on actual 7 too.
> 
> 

what i meant with display.dll.mui, is that my windows 7 install, **doesn't** have the string id 457 for some reason, so i just left it

**Comment by ImSwordQueen** [comment]
> > > now it should have everything that you requested. if you notice something is missing, please tell me.
> > 
> > 
> > LGTM. ThemeCPL has those missing but i can fix that myself later.
> > For display.dll please refer to this: [#7 (comment)](https://github.com/ImSwordQueen/Win10to7LanguagePacks/pull/7#issuecomment-2395121402) and tell me if it doesn't have them on actual 7 too.
> 
> what i meant with display.dll.mui, is that my windows 7 install, **doesn't** have the string id 457 for some reason, so i just left it

Ohhhh okay okay okay. Then it's ready to merge.

**Pull request merged**
