### PR TITLE
Added ko-KR

### PR DESCRIPTION
**Pull request by hywol**
authui.dll.mui
Magnification.dll.mui
Magnify.exe.mui

are missing sorry. because Original iso file or Win10 Old Version PC is missing.

### CODE REVIEW

**Comment by hywol** [comment]
I added missing files from Windows Korean version VM

**Comment by ImSwordQueen** [comment]
> I added missing files from Windows Korean version VM

So everything is included right? I will check it up when i have time

**Comment by hywol** [comment]
probably yes.

**Comment by hywol** [comment]
Language pack is successfully applied at my computers. But, I found missing translation in windows.storage.dll.mui.res file.

**Comment by ImSwordQueen** [comment]
I started looking at the translation and i noticed that the special korean branding is missing in basebrd
image

i will add more comments if i find more stuff

**Comment by ImSwordQueen** [comment]
It seems that tipresx.dll.mui.res has missing strings. Confirm if if i'm wrong here and it's like this in the 7's korean LP
image

**Comment by ImSwordQueen** [comment]
I did some changes to the stuff i mentioned earlier. Some of the tweaks that were made for 3.5.4 are not included so if you want to include them you can open a new PR request. I will merge this pull request for now.

**Pull request merged**
