### PR TITLE
ru-RU

### PR DESCRIPTION
**Pull request by A1Asriel**

### CODE REVIEW

**Comment by ImSwordQueen** [comment]
Thank you!

**Comment by Inui-senpai** [comment]
There are untranslated text in some places:
- "Display" and its tooltip in the Appearance and Personalization section
Snap8210
- "Configure..." and its tooltip in the Show hidden icons window
Snap8211
Snap8212
- The whole Taskbar Properties window
Snap8213
Snap8214
- Some preinstalled programs' and its folders' names (but the tooltips are translated)
Snap8215
Snap8216
Snap8217

I'm sorry if this is the wrong place for the error reports like this. 🙇‍♀️

**Comment by ImSwordQueen** [comment]
> There are untranslated text in some places:
> 
>     * "Display" and its tooltip in the Appearance and Personalization section
>       Snap8210
> 
>     * "Configure..." and its tooltip in the Show hidden icons window
>       Snap8211
>       Snap8212
> 
>     * The whole Taskbar Properties window
>       Snap8213
>       Snap8214
> 
>     * Some preinstalled programs' and its folders' names (but the tooltips are translated)
>       Snap8215
>       Snap8216
>       Snap8217
> 
> 
> I'm sorry if this is the wrong place for the error reports like this. 🙇‍♀️

Bug reports with language packs should be reported here https://github.com/ImSwordQueen/Win10to7Issues/issues/new?template=language_pack_bug_report.yml

**Comment by Inui-senpai** [comment]
> Bug reports with language packs should be reported here https://github.com/ImSwordQueen/Win10to7Issues/issues/new?template=language_pack_bug_report.yml
Thank you. I'll move the error report over there.

**Pull request merged**
